openapi: 3.0.3
info:
  title: NeosVR API
  description: API Documentation for NeosVR
  version: '2.0'
  contact:
    name: Neos
    url: 'https://neos.com/'
  license:
    name: MIT
servers:
  - url: 'https://api.neos.com'
components:
  securitySchemes:
    neosAuth:
      $ref: ./components/securitySchemes/neosAuth.yml
security:
  - neosAuth: []
paths:
  '/api/users/{UserId}/status':
    $ref: 'paths/api@users@{UserId}@status.yaml'
